### ISSUE TITLE
[running the test] No blast output

### ISSUE THREAD

**Issue by Sanrrone** [DrKaiyangZheng/VITAP#1]
Dears, I am running the test with the file you provide. However, it seems there is an issue by calling blast.
```
./scripts/VITAP.sh assignment -i test.fasta -d ./DB_20240115_IMGVR_expanded -o test_result
===== The VITAP (VIral Taxonomy Assigning Pipeline, main program) Copyright 2023 Kaiyang Zheng, Viral/microbial diversity Lab. Ocean University of China ===== 
[INFO] A number of temporary files will be generated in your result directory, please keep them or delete them followed by the guidlines.
===== ORF calling for test.fasta =====
[INFO] Ten ICTV reference genomes were randomly selected and merged to your genome set! 
[INFO] Genome and ORF files have consistent non-redundant FASTA IDs. √
[INFO] Length statitic for merged_genome.fasta
[INFO] Statistic of the number of ORF per genome
===== Aligning to ICTV reference database based on BLAST-algorithm =====
[INFO] Please delete the output file (test_result/target_ICTV_blastp.align) if this step aborted!
[INFO] Please keep the output file (test_result/target_ICTV_blastp.align) if this step finished!
===== Locating contig on taxonomic framework and generating genome community network =====
[INFO] Generating Species graph for target genomes
Traceback (most recent call last):
  File "/scratch/project_2007362/software/VITAP/scripts/VITAP_assignment_20240421.py", line 400, in <module>
    assignment()	
    ^^^^^^^^^^^^
  File "/scratch/project_2007362/software/VITAP/scripts/VITAP_assignment_20240421.py", line 382, in assignment
    taxonomy_assigning(target_blast_fp, VMR_csv_file, genome_cutoff_file, taxa, length_file, orf_count_df, taxa_annot_file, taxa_annot_file)
  File "/scratch/project_2007362/software/VITAP/scripts/VITAP_assignment_20240421.py", line 86, in taxonomy_assigning
    blast_results = pd.read_csv(blast_results_file, sep="\t", names=["qseqid", "sseqid", f"bitscore"])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project_2007362/software/mambaforge/envs/VITAP/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project_2007362/software/mambaforge/envs/VITAP/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project_2007362/software/mambaforge/envs/VITAP/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project_2007362/software/mambaforge/envs/VITAP/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/scratch/project_2007362/software/mambaforge/envs/VITAP/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test_result/target_ICTV_blastp.align'
```
How can I proceed?

thanks in advance!

**Comment by DrKaiyangZheng** [comment]
Hi, Sandro,
This issue is usually caused by an abnormal run of Diamond, but there could be multiple reasons for it. It might be due to Prodigal failing to successfully predict protein sequences, leading to errors in the downstream Diamond step, or it could be that Diamond itself did not run successfully. You may be able to identify these issues through the VITAP_run.log. Some more complex reasons could be related to environment configuration problems. I have merged VITAP into Bioconda's recipes, and it is hosted by Bioconda. You can try reinstalling it and see if that resolves the issue. The good news is that I have merged VITAP into the Bioconda recipes, so now you can easily install and test it using conda (conda install bioconda::vitap). Thank you for your feedback, and thank you for all the suggestions to improve the VITAP manuscript. Hope this tool can be of some help to you in advance! :)

**Comment by DrKaiyangZheng** [comment]
I apologize for my delayed response. First, I have updated the FigShare link, and now you should be able to download the pre-built database without any issues. Additionally, I have corrected the link to the ICTV VMR (https://ictv.global/vmr), which now works properly. You can access the files and find the “Virus GENBANK accession” column in the Excel file.

**Comment by asierFernandezP** [comment]
Hi,

I get the same error when installing it using conda:

```
===== The VITAP (Viral Taxonomic Assignment Pipeline, main program) v.1.5, Copyright 2024 Kaiyang Zheng, Viral/microbial diversity Lab. Ocean University of China =====          
[INFO] A number of temporary files will be generated in your result directory, please keep them or delete them followed by the guidlines.                                        
===== ORF calling for a.fa =====
[INFO] Ten ICTV reference genomes were randomly selected and merged to your genome set! 
[INFO] Genome and ORF files have consistent non-redundant FASTA IDs. √
[INFO] Length statitic for merged_genome.fasta
[INFO] Statistic of the number of ORF per genome
===== Aligning to ICTV reference database based on BLAST-algorithm =====
[INFO] Please delete the output file (test_result/target_ICTV_blastp.align) if this step aborted!
[INFO] Please keep the output file (test_result/target_ICTV_blastp.align) if this step finished!
===== Locating contig on taxonomic framework and generating genome community network =====
[INFO] Generating Species graph for target genomes
Traceback (most recent call last):
  File "/scratch/hb-llnext/conda_envs/VITAP_env/bin/VITAP_assignment_20241007.py", line 449, in <module>
    assignment()    
  File "/scratch/hb-llnext/conda_envs/VITAP_env/bin/VITAP_assignment_20241007.py", line 399, in assignment
    taxonomy_assigning(target_blast_fp, VMR_csv_file, genome_cutoff_file, taxa, length_file, orf_count_df, taxa_annot_file, taxa_annot_file)
  File "/scratch/hb-llnext/conda_envs/VITAP_env/bin/VITAP_assignment_20241007.py", line 86, in taxonomy_assigning
    blast_results = pd.read_csv(blast_results_file, sep="\t", names=["qseqid", "sseqid", f"bitscore"])
  File "/scratch/hb-llnext/conda_envs/VITAP_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/scratch/hb-llnext/conda_envs/VITAP_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/scratch/hb-llnext/conda_envs/VITAP_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/scratch/hb-llnext/conda_envs/VITAP_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/scratch/hb-llnext/conda_envs/VITAP_env/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'test_result/target_ICTV_blastp.align
```
Is there any other python version or dependencies that should be added?

**Comment by 1023011930** [comment]
![Image](https://github.com/user-attachments/assets/ecf6ec03-b1bf-4028-9b98-7c399f5c7b8f)
Apparently, this is due to the fact that the version of diamond that frames the database is too different from the version of diamond that we have installed.
for "DB_hybrid_MSL37_RefSeq209_IMGVR"(2025.3.10version)
May I ask what version of diamond you are using for database building?

**Comment by 1023011930** [comment]
> ![Image](https://github.com/user-attachments/assets/ecf6ec03-b1bf-4028-9b98-7c399f5c7b8f) Apparently, this is due to the fact that the version of diamond that frames the database is too different from the version of diamond that we have installed. for "DB_hybrid_MSL37_RefSeq209_IMGVR"(2025.3.10version) May I ask what version of diamond you are using for database building?

or i build a new dmnd database using my diamond=2.1，
"diamond makedb --in /home/zhongpei/hard_disk_sda2/zhongpei/database/vitap/DB_hybrid_MSL37_RefSeq209_IMGVR/VMR_genome_hybrid_RefSeqs_IMGVR.faa -d /home/zhongpei/hard_disk_sda2/zhongpei/database/vitap/DB_hybrid_MSL37_RefSeq209_IMGVR/VMR_genome_hybrid_RefSeqs_IMGVR.dmnd
" 
and the bug is solved

**Comment by DrKaiyangZheng** [comment]
Thank you all for your discussion and support. Regarding Fig. files, viral genomes, etc.:
The database was built using a specific version of DIAMOND. It's important to use the exact corresponding version of DIAMOND (matching the database .dmnd file). Even though different versions might be compatible, slight differences between DIAMOND versions could result in minor variations in the threshold files, potentially leading to errors in the final classification. Therefore, if possible, always use the same version of DIAMOND (matching the database version).
