### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './DB_VMR-MSL/Species_genome.threshold'

### ISSUE THREAD

**Issue by minas-tirith** [DrKaiyangZheng/VITAP#2]
```
./VITAP assignment -i /home/rk05/project/vitap/test.fasta -d ./DB_VMR-MSL -o /home/rk05/project/vitap/test_out.fasta
===== The VITAP (Viral Taxonomic Assignment Pipeline, main program) v.1.5, Copyright 2024 Kaiyang Zheng, Viral/microbial diversity Lab. Ocean University of China ===== 
[INFO] A number of temporary files will be generated in your result directory, please keep them or delete them followed by the guidlines.
===== ORF calling for /home/rk05/project/vitap/test.fasta =====
[INFO] Using exited file : /home/rk05/project/vitap/test_out.fasta/merge_genome.faa
[INFO] Genome and ORF files have consistent non-redundant FASTA IDs. √
[INFO] The merge_genome_length.tsv exists, skipping.
[INFO] Statistic of the number of ORF per genome
===== Aligning to ICTV reference database based on BLAST-algorithm =====
[INFO] Using exited file : /home/rk05/project/vitap/test_out.fasta/target_ICTV_blastp.align
===== Locating contig on taxonomic framework and generating genome community network =====
[INFO] Generating Species graph for target genomes
Traceback (most recent call last):
  File "/home/rk05/apps/VITAP/scripts/VITAP_assignment_20241007.py", line 449, in <module>
    assignment()    
    ^^^^^^^^^^^^
  File "/home/rk05/apps/VITAP/scripts/VITAP_assignment_20241007.py", line 399, in assignment
    taxonomy_assigning(target_blast_fp, VMR_csv_file, genome_cutoff_file, taxa, length_file, orf_count_df, taxa_annot_file, taxa_annot_file)
  File "/home/rk05/apps/VITAP/scripts/VITAP_assignment_20241007.py", line 158, in taxonomy_assigning
    df_thresholds2 = pd.read_csv(genome_cutoff_file, sep="\t")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rk05/miniconda3/envs/VITAP/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rk05/miniconda3/envs/VITAP/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rk05/miniconda3/envs/VITAP/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rk05/miniconda3/envs/VITAP/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/rk05/miniconda3/envs/VITAP/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './DB_VMR-MSL/Species_genome.threshold'
```
I built the database as you have instructed. Because, I couldn't find your pre-built database. Now, it is showing the above error. I checked the DB_VMR-MSL folder. There was no file named Species_genome.threshold.

**Comment by DrKaiyangZheng** [comment]
I apologize for my delayed response. First, I have updated the FigShare link, and now you should be able to download the pre-built database without any issues. Additionally, if you need to build the database manually, you must ensure that the `VITAP upd` step has been completed, and that the corresponding database directory contains the {Species to Realm}_genome.threshold files. Judging from the error message, it appears that there was an issue with this step.
